Add quick start docs
Redfire75369/spiderfire pull request #21
Opened 2022-02-03 22:42 UTC by Gers2017

2022-02-05 11:51 UTC, Redfire75369 commented
I think the quick start docs should be moved to a different location, it doesn't exactly make sense to be under `contribution/`. My suggestion is probably `docs/quick-start.md`.

The docs also seem to imply Windows usage, despite spiderfire working on all 3 major operating systems. I'm not necessarily sure how to fix this, but removing `.exe` should probably work.

###### Formatting
- `-   ` can be replaced with `- `, makes it cleaner in my opinion.

2022-02-05 11:57 UTC, Redfire75369 requested changes
Here's a few more specific changes that I think would be good. See the above comment for the more general changes.

2022-02-05 11:57 UTC, Redfire75369 commented on readme.md
> +For a quick guide to get started refer [here](contribution/quick-start.md)
This can probably be replaced with the following.
> For a quick guide to get started, refer [here](contribution/quick-start.md).

2022-02-05 11:57 UTC, Redfire75369 commented on contribution/quick-start.md
> +Start a javascript repl, exit by pressing `ctrl + c` twice
I think `ctrl + c` here can be replaced with `Ctrl + C`, which makes it clearer that it's a keybind/keypress.

2022-02-08 23:04 UTC, Gers2017 commented
> * `-   ` can be replaced with `- `, makes it cleaner in my opinion.

I'm confused about this one. you mean add 3 spaces after the `-`?

2022-03-19 10:48 UTC, Redfire75369 approved these changes

2022-03-19 10:48 UTC, merged